### ISSUE TITLE
Add a link to CloudyNights

### ISSUE THREAD

**Issue by fliker09** [Rolf-Hempel/PlanetarySystemLRGBAligner#2]
Your other repo, MoonPanoramaMaker, has a link in it's description pointing to Cloudy Nights discussion thread. It would nice to have it for this repo as well

https://www.cloudynights.com/topic/640309-lrgb-composite-images-of-the-moon-or-planets/

**Comment by Rolf-Hempel** [comment]
Thanks for the suggestion. I included a note in the README.
