### ISSUE TITLE
OpenCV assertion fails on certain images

### ISSUE THREAD

**Issue by spiantino** [Rolf-Hempel/PlanetarySystemLRGBAligner#3]
While trying to align some separate RBG shots of the moon, I got the following error (and program exit). It seems to happen in the rigid transformation step (if I skip that part the crash doesn't occur):

```
C:\Program Files (x86)\PlanetarySystemLRGBAligner\planetary_system_LRGB_aligner>planetary_system_LRGB_aligner.exe
Traceback (most recent call last):
  File "workflow.py", line 128, in run
cv2.error: OpenCV(3.4.2) D:\Build\OpenCV\opencv-3.4.2\modules\calib3d\src\ptsetreg.cpp:282: error: (-215:Assertion failed) count >= 0 && count2 == count in function 'cv::LMeDSPointSetRegistrator::run'
```

It somehow only happens when aligning the mono frame (which is really the red channel) with an RGB image that only contains the blue channel. The green works well. 

Thanks for a great piece of software! I was shocked to learn none of the software I was used to using could align RGB images, and your package came to the rescue.

**Comment by Rolf-Hempel** [comment]
I'm glad that you find my software useful!

I have no idea what happened inside the opencv routine. My guess is that the red and blue channels are too different, so the software does not find good anchor points present in both images to determine the homography mapping.

I guess you are trying to align the three color channels with each other. What if you align the red channel mono frame with an RGB image that only contains the green channel? I would expect that the differences are smaller, so the mapping might be successful.
